services:
  - type: web
    name: shambarecords-backend
    env: node
    buildCommand: yarn
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: false
